image: docker
services:
  - docker:dind

stages:
  - build
#  - test
#  - release

variables:
  TEST_IMAGE: 172.17.0.1:5555/igor/figlem:base
  RELEASE_IMAGE: 172.17.0.1:5555/igor/figlem:dev

before_script:
  - docker login -u igor -p asdfasfd2 172.17.0.1:5555

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  tags:
    - shell

#test:
#  stage: test
#  script:
#    - docker pull $TEST_IMAGE
#  only:
#    - production

#release:
#  stage: release
#  script:
#    - docker pull $TEST_IMAGE
#    - docker tag $TEST_IMAGE $RELEASE_IMAGE
#    - docker push $RELEASE_IMAGE
#  only:
#    - production
